# Generated by Django 3.0.4 on 2020-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200325_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='faq',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sega Master System'), (1, 'Sony Playstation'), (2, 'Sony Playstation 2'), (3, 'Sony Playstation 3'), (4, 'X-Box 360'), (5, 'PC')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
