# Generated by Django 3.0.4 on 2020-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200325_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sega Mega Drive'), (1, 'Sony Playstation'), (2, 'Sony Playstation 2'), (3, 'Sony Playstation 3'), (4, 'X-Box 360'), (5, 'PC')], null=True),
        ),
    ]
