# Generated by Django 3.0.4 on 2020-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200327_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Console',
            new_name='Platform',
        ),
    ]
