# Generated by Django 3.0.4 on 2020-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200331_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sega Mega Drive'), (1, 'Sony Playstation'), (2, 'Sony Playstation 2'), (3, 'Sony Playstation 3'), (4, 'X-Box 360'), (5, 'PC'), (6, 'GameGear'), (7, 'VITA'), (8, 'DS'), (9, 'PSP'), (10, 'DREAMCAST')], null=True, verbose_name='platform'),
        ),
    ]
