# Generated by Django 3.0.4 on 2020-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200331_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='title',
        ),
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sega Mega Drive'), (1, 'Sony Playstation'), (2, 'Sony Playstation 2'), (3, 'Sony Playstation 3'), (4, 'X-Box 360'), (5, 'PC'), (6, 'GameGear'), (7, 'VITA'), (8, 'DS'), (9, 'PSP'), (10, 'DREAMCAST')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
