# Generated by Django 3.0.4 on 2020-03-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_game_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='name',
            new_name='title',
        ),
    ]
