# Generated by Django 3.0.4 on 2020-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200331_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={},
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='platform',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sega Mega Drive'), (1, 'Sony Playstation'), (2, 'Sony Playstation 2'), (3, 'Sony Playstation 3'), (4, 'X-Box 360'), (5, 'PC'), (6, 'GameGear'), (7, 'VITA'), (8, 'DS'), (9, 'PSP'), (10, 'DREAMCAST')], default=0),
        ),
    ]
