# Generated by Django 3.0.4 on 2020-03-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200331_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='platforms',
        ),
    ]
