# Generated by Django 3.0.4 on 2020-03-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200331_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.Platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
