# Generated by Django 3.0.4 on 2020-03-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200331_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
    ]
