# Generated by Django 3.0.4 on 2020-04-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200401_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
