# Generated by Django 3.0.4 on 2020-04-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
