# Generated by Django 3.0.4 on 2020-04-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_new_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
    ]
